# Generated by Django 2.2.1 on 2020-02-21 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='contact',
            name='number_plate',
            field=models.CharField(default='AB01AB23456', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='service_used',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
