# Generated by Django 2.2.1 on 2020-02-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200221_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
