# Generated by Django 2.2.1 on 2020-02-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200221_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avalibility', models.CharField(choices=[('empty', 'Empty'), ('occupied', 'Occupied')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='info',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default=None),
        ),
    ]
