# Generated by Django 2.2.1 on 2020-02-21 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_slot_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number_plate',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Contact', to_field='number_plate'),
        ),
    ]
