# Generated by Django 2.2.1 on 2020-02-21 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200221_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='car',
        ),
        migrations.AddField(
            model_name='slot',
            name='number_plate',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Contact', verbose_name='number_plate'),
        ),
    ]
