# Generated by Django 2.2.1 on 2020-02-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200221_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='service_used',
            field=models.IntegerField(default=0),
        ),
    ]
