# Generated by Django 2.2.1 on 2020-02-21 07:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200221_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(default=None, max_length=11, unique=True)),
                ('entry_time', models.DateTimeField(default=datetime.datetime.now)),
                ('service_used', models.IntegerField(default=0)),
                ('name', models.CharField(default=None, max_length=20)),
                ('email', models.EmailField(default=None, max_length=100)),
                ('phone', models.IntegerField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='entry_time',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='service_used',
        ),
        migrations.AddField(
            model_name='contact',
            name='avalibility',
            field=models.CharField(choices=[('empty', 'Empty'), ('occupied', 'Occupied')], default='empty', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='number_plate',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Car'),
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
