# Generated by Django 2.2.1 on 2020-02-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200221_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sl_no',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
