# Generated by Django 2.2.1 on 2020-02-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_contact_sl_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number_plate',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Car'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sl_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
