# Generated by Django 2.2.1 on 2020-02-21 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200221_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number_plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Car'),
        ),
    ]
