# Generated by Django 2.2.1 on 2020-02-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_contact_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='info',
            field=models.CharField(choices=[('normal', 'Normal Customer'), ('premium', 'Premium Customer')], max_length=50),
        ),
    ]
