# Generated by Django 2.2.1 on 2020-02-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200222_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('Allowed', 'Allowed'), ('Not Allowed', 'Not Allowed')], default='Allowed', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='info',
            field=models.CharField(choices=[('Normal Customer', 'Normal Customer'), ('Premium Customer', 'Premium Customer')], max_length=50),
        ),
    ]
