# Generated by Django 2.2.1 on 2020-02-28 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200223_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='sl_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Contact'),
        ),
    ]
