# Generated by Django 2.2.1 on 2020-02-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_car_sl_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='email',
            field=models.EmailField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='phone',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
